### ISSUE TITLE
No releases in this repo?

### ISSUE THREAD

**Issue by hailwood** [egoist/bget#2]
I'm attempting to use bget with [lando/lando](https://github.com/lando/lando/releases) (it's the lando-x64-vX.X.X.deb I'm interested in)
The latest release is v.3.4.2 although there are later pre-releases.

![image](https://user-images.githubusercontent.com/709773/143964742-85e79735-4a1a-4bec-a448-bd0cbc9503ac.png)

Unfortunately when running `bget lando/lando` I just get 'no releases in this repo'

**Comment by egoist** [comment]
it can only install binaries without extension (or .exe on windows) for now

**Comment by hailwood** [comment]
That's fair, but shouldn't it have still picked up the .exe that is there rather than saying there are no releases?

**Comment by egoist** [comment]
true, I'll also let it download other files just without installing them.

**Comment by lifesign** [comment]
same here. 

example: https://github.com/multiprocessio/dsq

**Comment by egoist** [comment]
this issue should be fixed in 1.0.8

btw this library won't be able to handle `.deb` and `.dmg` since all it does is moving the asset to `/usr/local/bin`
